from sqlalchemy import Column, Integer, String, Float, Text, Boolean, DateTime
from sqlalchemy.sql import func
from agent_core.db.database import Base

class SkillAssessmentRecord(Base):
    __tablename__ = "skill_assessment_records"

    id = Column(Integer, primary_key=True, index=True)
    primary_language = Column(String(50))
    overall_level = Column(String(50))
    technical_score = Column(Float)
    raw_snippet = Column(Text)
    test_execution_output = Column(Text, nullable=True) # Output of the actual code run
    tester_suggestions = Column(Text, nullable=True) # QA suggestions generated by AI parsing output
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class AutomationMemory(Base):
    """
    Logs generated automation scripts. Crucial for the self-improving loop if
    we later implement functionality for users to supply the 'user_edited_script'.
    """
    __tablename__ = "automation_memories"

    id = Column(Integer, primary_key=True, index=True)
    intent = Column(Text)
    target_env = Column(String(50))
    generated_script = Column(Text)
    reasoning = Column(Text)
    user_edited_script = Column(Text, nullable=True) # Used for RAG improvement tracking
    is_successful = Column(Boolean, default=True)
    
    # Feature Extensions (Agentic Upgrade)
    validation_script = Column(Text, nullable=True)
    blast_radius_report = Column(Text, nullable=True) 
    iteration_history = Column(Text, nullable=True)
    context_used = Column(Text, nullable=True)
    working_directory = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
